### PR TITLE
Added SAS University Edition and SAS OnDemand Academic

### PR DESCRIPTION
**Pull request by blackhat999**
Free to all students, teachers, and professors.

### CODE REVIEW

**Comment by najela** [comment]
Hey @blackhat999  Thanks for the PR. I get a DNS resolution error when trying to open http://http//www.sas.com/en_us/software/university-edition.html

**Comment by blackhat999** [comment]
@najela Oops! I typed "http://http://". Adding another commit.

**Comment by blackhat999** [comment]
@najela Fixed it! Travis CI is passing now.

**Comment by najela** [comment]
Thanks  :+1:

**Pull request merged**
