### PR TITLE
Updated README.md (Added discount for Jungl VPN)

### PR DESCRIPTION
**Pull request by junglhilt**
Added discount for Jungl VPN

### CODE REVIEW

**Comment by najela** [comment]
Hello @junglhilt Thanks for the commit.  I tried using the coupon code you mentioned but it was rejected

image

**Comment by junglhilt** [comment]
Hey Arnold,

The coupon is valid for the annual plans only. Would you like me to add that to the pull request so it is more clear?

**Comment by najela** [comment]
Hey, 
I also have a problem about adding **coupons** to this list. This list is mainly for discounts that are targeted to students.  Anyone can use the the coupon you provided even if they're not students.

**Comment by junglhilt** [comment]
Hmmm...ok I understand. Thanks for your time mate :)

**Pull request closed without merging**
