### PR TITLE
Added Yellow Circle

### PR DESCRIPTION
**Pull request by blackhat999**
[Yellow Circle](http://www.yellowcircle.net) offers students and teachers a free sandbox for working with VMs and virtual networking appliances. Port forwarding available for a nominal fee.

### CODE REVIEW

**Comment by louissegal** [comment]
The link in the file is fine but nb that your comment link points to the wrong address, it should be [http://www.yellowcircle.net/](http://www.yellowcircle.net/)

**Comment by blackhat999** [comment]
@louissegal oops. your right, will edit description

**Comment by blackhat999** [comment]
Hmm.. The CI build is saying that connection timed out for http://yellowcircle.com. In the browser is redirecting to www.yellowcircle.com, so I added the 'www.' in a separate commit but now the build says 'connection reset by peer.'

**Comment by blackhat999** [comment]
Interesting. The Travis build on my fork is passing.

**Comment by najela** [comment]
Thanks :+1:

**Pull request merged**
