### PR TITLE
Add Axure prototyping software to Design section

### PR DESCRIPTION
**Pull request by blindingstars**
Free educational license for teachers and students in high school, university, or community college. Axure can be used for wireframing, interactive prototypes, and documentation.

### CODE REVIEW

**Comment by najela** [comment]
Thanks :+1:

**Comment by WV5N** [comment]
Axure, aka: Axure RP Pro, was already added to the list. It's under "Software Modeling Tools".
[Commit on May 11, 2015.](https://github.com/najela/discount-for-student-dev/commit/53bdb8816d3f88e39f9e7df82e6f431f8d6aed21)

**Comment by najela** [comment]
Thanks @WV5N

**Comment by blindingstars** [comment]
Sorry about that! I had searched; must have made a typo.

**Pull request merged**
